### ISSUE TITLE
[Bug] Some MIDI keyboards might not work

### ISSUE THREAD

**Issue by ZaneH** [ZaneH/piano-trainer#4]
- MIDI keyboard isn't tracking notes

**Comment by dellis23** [comment]
For what it's worth, the MIDI keyboard seems to be working for me, as the program is recognizing the input and is playing sounds.  But it never moves on to the next chord or anything.

**Comment by ZaneH** [comment]
> For what it's worth, the MIDI keyboard seems to be working for me, as the program is recognizing the input and is playing sounds. But it never moves on to the next chord or anything.

Dumb question but are you pressing the keys highlighted blue at the same time? Also which MIDI keyboard are you using

Another thing that's worth trying: Use a different octave. I need to make it so that the octave doesn't matter

**Comment by dellis23** [comment]
I'm using the M-Audio Keystation 49 MK3.  I think you're right that it was an octave issue.  Seems to be working fine now!

**Comment by ZaneH** [comment]
Glad to hear, I'll be sure to make it so that every octave works just for UX. Thanks for confirming that

**Comment by ZaneH** [comment]
Had a similar report and got the logs to fix this issue. It's fixed in v1.0.8 👍
