### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by sparunakian** [ZaneH/piano-trainer#7]
Hi!

Thank you for Piano Trainer, this is really nice! Have you planned to support translation of the interface, especially notes?

Regards

**Comment by ZaneH** [comment]
I haven't considered it but I think this is a good idea. I'll add an i18n translation file for easy translation contributions

**Comment by ZaneH** [comment]
I'll add a dropdown selector to the Settings sidebar once another language is added. To add a translation, create a folder in `./src/i18n` with your locale and copy the existing `translations.json` file and add your custom translations
